### ISSUE TITLE
运行 npm run fetch 报错，显示 no suitable image found

### ISSUE THREAD

**Issue by bigrotor187** [modood/Administrative-divisions-of-China#82]
```java
/Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:91
      throw err;
      ^

Error: dlopen(/Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node, 1): no suitable image found.  Did find:
        /Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1724416 which is past end of file 130958
        /Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sqlite3/lib/binding/node-v72-darwin-x64/node_sqlite3.node: truncated mach-o error: segment __TEXT extends to 1724416 which is past end of file 130958
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1021:18)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sqlite3/lib/sqlite3-binding.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sqlite3/lib/sqlite3.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at ConnectionManager._loadDialectModule (/Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sequelize/lib/dialects/abstract/connection-manager.js:79:32)
    at new ConnectionManager (/Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sequelize/lib/dialects/sqlite/connection-manager.js:22:21)
    at new SqliteDialect (/Users/xxx/xxx/mycode/Administrative-divisions-of-China/node_modules/sequelize/lib/dialects/sqlite/index.js:14:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! china-division@2.3.1 format: `node lib/build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the china-division@2.3.1 format script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by bigrotor187** [comment]
已解决，忽略
